apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2b-db-secret
  namespace: b2bi-prod
spec:
  encryptedData:
    DB_PASSWORD: AgAZuGHPSQDqWENljhum1AZ4AdAGia+VLYEuV1xSrN/EOdVcbIkfbWgOh+hTv281cv1us9cS0esdKT94TO5D+oE8iPzmO2TuPGGRUd2rQlM1mGUJituZQYq+Aq2Vn0zy1Q36rDFd2P2Jz/1jyFMbcJ5OlMkOmCrnZ5uo2yPi9ResVXCanJSO2wzqtUZc3MPJ89Wx3w6BdFtY0wAJI78dd22INrjS/46IMZbs+qKLfuB/uGKULpQKrZcZlMVR53qfn7IkpNHxMXleGCTv5CPICbdsiVy9p8Ec9S9gcSvK8rDDnSZoKIFVKEsLvSMfdu655gsdJU47HyQVKUCKdkVT3wgzwk8VUuBtzt8h7LRnE9kp4Ok/z4WryBL/aQta+2ilvo/c7K9lFpGXa4LuMJ4HJgDUX9Lldb3JGsga222bR1PXyKa/EI8AdgPkgtFZK7dxPrCSf/Qk3WTTezr44Naleu1iG2A7rLjcz4vxOmRd0jIppnD4XLds22+i5uD/g/A7P5EqPJecy82cBOuUFIUKaufu3d36jRT7yFiLUa8b5f88KaKVm0yrCSuSrgON1gxydin2DLgjd4Q4/7gZ12n1+VfkWOHzjE2FHIe1ovXG8RyhOc9L/GBBDLa/3zOoJGk+4z8IofQ+4IaKykKz8ZZukmjYxVVr+lRsm7V7PDPf/Wvt0VX2CWmM79ercF5SPL7u/Vd9R2UJ6osizg==
    DB_USER: AgAKZ1CWlPmlxTGJyIx1sK7DUQcDmBH3pStAy4grPa12hGiRR4l9ua2BJN44iF6VFYcwA5CNAr4UF0hPPvIYob2auB1ccX3rHna5OZ95vLloay6hG1zQbAILNVQ+d8pL8UHkSk+Sa3WVh9nOVjwP78eCMR44YcXx4dwD+Jmo8bMoZfzT8Ac17aY+IhA+RpcwsRt0k3LGX6YH1jar04/XqnCJrdMMvzY/TH2qq0lIpSMVc2NrGlpnFH6q/L/u/lreyIsmz8HyDi2KKa4EBaPtvYKlzyy2t4o+Yeq3TCNwWosT9Vv5x2NLiStuu4ZkKA2at9drayksqgxDVX2z0+i40dkEEMrcWvX2WjlTxM0bKQneMbg4gxFC/6phDafslJVInOzDvTfkbab/4fj7Y4RQ0QitJFAXIi/aFN6fgGGav5gQfE4uaVpGZXuzf37pWi32h0sWF5tFUmtegaG5B4uRNbJZlKwH8lo0YGUdagi/bla/jFkNY5gJeDcPxtbnq6jPrth2/PDzAmDKSMTtjRQJ2wC6npGdEH52Kue7QFTzomlcuxZCWUCLdsFgjLmdchsEcGogYWnv2wsSd/RwESX7yZHcFMZYE4HKho8sNCZ/LF80SxyvLirCwHRIEe8+lAIXHoWghrSXW5U48QyTXHvOySnY/A2Zc0PNrpMbbxmIrIcea+CfL2C0TjD6/yJs/oDyLgW4mPoOdV30+A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: b2b-db-secret
      namespace: b2bi-prod
    type: Opaque

